apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
resources:
  - kafka-namespace.yaml
  - zookeeper-service.yaml
  - zookeeper-deployment.yaml
  - kafka-service.yaml
  - kafka-deployment.yaml
